package Crypt::Rijndael_PP_a::Cache;

sub import {
	require Crypt::Rijndael_PP_a;
	return Crypt::Rijndael_PP_a::import(@_);
}

=head1 NAME

Crypt::Rijndael_PP_a::Cache

=head1 DESCRIPTION

A cache module for Crypt::Rijndael_PP_a, this vastly increases its speed efficiency at a small (< 100KiB total?) increase in memory.

=head1 SYNOPSIS

use Crypt::Rijndael_PP_a::Cache;

# ... then use the normal Crypt::Rijndael functions.

=head1 IMPORTING

Please note that Crypt::Rijndael_PP_a will generate its own s-box cache on startup if you don't include this module *first*.

Using this module is equivalent to using Crypt::Rijndael_PP_a, in that it will automatically require() Crypt::Rijndael_PP_a and pass on any arguments to import() (eg, ":AES").

If you just "require" this module rather than "use"ing it, Crypt::Rijndael_PP_a will not be automatically require()d.

=head1 NOTES

The bulk of this file is automatically generated during install.

=head1 BUGS

None known.

=head1 SEE ALSO

Crypt::Rijndael_PP_a

=cut
